import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import { ConfigProvider } from "antd";
import Header from "../component/layout/Header";
import Footer from "../component/layout/Footer";
import Head from "next/head";
import theme from "./theme/theme";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <title>Mist Agencies</title>
        <meta name="description" content="Mineral water with great quality" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <Header />
        <ConfigProvider theme={theme.dark}>{children}</ConfigProvider>
        <Footer />
      </body>
    </html>
  );
}
